# Generated by Django 4.2.7 on 2026-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение товара (JPEG, PNG, до 5 МБ)', null=True, upload_to='products/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите цену товара (должна быть больше 0)', max_digits=10, verbose_name='цена за покупку'),
        ),
    ]
